#!/usr/bin/env python3
"""Validate a stable release version."""
import os
import re

tag = os.environ.get('RELEASE_TAG', '')
if tag and not re.fullmatch(r'v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)', tag):
    raise SystemExit('expected a stable vMAJOR.MINOR.PATCH tag')
